<?php

class Home extends CI_Controller
{
    public function __construct()
    {
        parent::__construct(); // TODO: Change the autogenerated stub
        $this->load->model('property_model','pro');
        $this->load->model('Property_type_model','type');
        $this->load->model('Slider_model','slider');
    }


    function index(){

        $d['slider'] = $this->slider->getRecords();
        $d['type'] = $this->type->getRecords();
        $d['products'] = $this->pro->getBy( array('status'=>1 , 'home'=>1 ) );

        $this->load->view('home',$d);
    }

    function contact(){

        if($this->input->is_ajax_request()){
            if(isset($_POST['email'])):

                $name = $_POST['name'];
                $email = $_POST['email'];
                $subject = $_POST['subject'];
                $message = $_POST['message'];
                $address = 'gowtham@itmartx.com';

                if(get_magic_quotes_gpc()) {
                    $message = stripslashes($message);
                }

                $e_subject = 'You Have Received a Message From ' . $name . '.';

                if(!empty($subject))
                {
                    $e_subject = $subject . '.';
                }

                $e_body = 	"You have Received a message from: "
                    .$name
                    . "\n"
                    ."Their additional message is as follows."
                    ."\r\n\n";

                $e_content = "\" $message \"\r\n\n";

                $e_reply = 	"You can contact "
                    .$name
                    . " via email, "
                    .$email;

                $msg = $e_body . $e_content . $e_reply;

                if(mail($address, $e_subject, $msg, "From: $email\r\nReply-To: $email\r\nReturn-Path: $email\r\n","-f $address"))
                {
                    echo "Message Sent Successfully!";
                }
                else
                {
                    echo "Server Error: mail method failed!";
                }
            else:
                echo "Invalid Request !";
            endif;
        }else{
            $d['type'] = $this->type->getRecords();
            $location = $this->pro->getBy(array('status'=>1 ) , false , 'key' ,array('group_by'=>'key') );
            foreach($location as $l ){
                $s = explode(',',$l->key);
                if(count($s) == 1 )
                    $k[] = trim($s[0]) ;
                else {
                    foreach($s  as $v ){
                        $k[] = trim($v)  ;
                    }
                }
            }
            $k =  array_unique($k);
            sort($k);
            $d['key'] = $k ;
            unset($k);
            unset($location);
            $this->load->view('contact',$d);
        }
    }

    function about(){
        $d['type'] = $this->type->getRecords();
        $this->load->view('about',$d);
    }
    function services(){
        $d['type'] = $this->type->getRecords();
        $this->load->view('services',$d);
    }

    function changeCurrency($to){
        $this->session->set_userdata('from',$to);
    }

    function fu(){
        $this->load->view('a',array('a'=>'?????'));
    }

}